name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build
